services:
  app:
    container_name: front_docker
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../:/var/www:cached
      - /var/www/node_modules
    stdin_open: true
    tty: true